//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Families
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Families()
        {
            this.FamilyTelephones = new HashSet<FamilyTelephones>();
            this.Patients = new HashSet<Patients>();
        }
    
        public int FamilyId { get; set; }
        public string LastName { get; set; }
        public string Father_Name { get; set; }
        public string FatherId { get; set; }
        public string Mather_Name { get; set; }
        public string MotherId { get; set; }
        public int CityId { get; set; }
        public string Address { get; set; }
        public string Mail { get; set; }
        public System.DateTime Entry_Date { get; set; }
        public int Kupat_Cholim_id { get; set; }
        public int SnifId { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Snifim Snifim { get; set; }
        public virtual KupatCholim KupatCholim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyTelephones> FamilyTelephones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patients> Patients { get; set; }
    }
}
