//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forms
    {
        public int FormId { get; set; }
        public int ZakautId { get; set; }
        public string Form_Name { get; set; }
        public string Form_FileName_Navigation { get; set; }
    
        public virtual Zakauts Zakauts { get; set; }
    }
}
