//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShemaKolenuEntities : DbContext
    {
        public ShemaKolenuEntities()
            : base("name=ShemaKolenuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Families> Families { get; set; }
        public virtual DbSet<FamilyTelephones> FamilyTelephones { get; set; }
        public virtual DbSet<Forms> Forms { get; set; }
        public virtual DbSet<Klinaits> Klinaits { get; set; }
        public virtual DbSet<KupatCholim> KupatCholim { get; set; }
        public virtual DbSet<Offices> Offices { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<Snifim> Snifim { get; set; }
        public virtual DbSet<Tested> Tested { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserStatus> UserStatus { get; set; }
        public virtual DbSet<Zakauts> Zakauts { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<IndexOfExcel> IndexOfExcel { get; set; }
    }
}
