//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tested
    {
        public int Test_number { get; set; }
        public int Patient_tz { get; set; }
        public System.DateTime Test_date_ { get; set; }
        public int SnifId { get; set; }
        public string File_test_result_navigation { get; set; }
    
        public virtual Snifim Snifim { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
